from typing import Protocol

import chess
import torch

from denoisr.types import Action, LegalMask


class GameInterface(Protocol):
    def get_init_board(self) -> chess.Board: ...
    def get_board_size(self) -> tuple[int, int]: ...
    def get_action_size(self) -> int: ...
    def get_next_state(
        self, board: chess.Board, action: Action
    ) -> chess.Board: ...
    def get_valid_moves(self, board: chess.Board) -> LegalMask: ...
    def get_game_ended(self, board: chess.Board) -> float | None: ...
    def get_canonical_form(self, board: chess.Board) -> chess.Board: ...
    def get_symmetries(
        self, board: chess.Board, policy: torch.Tensor
    ) -> list[tuple[chess.Board, torch.Tensor]]: ...
